In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

df = pd.read_csv("../Data/telecom_customer_churn.csv")
df.head()
ProfileReport(df)

In [2]:
from sklearn.preprocessing import OneHotEncoder


# Crear una columna combinada de Zip Code, Latitude, y Longitude
df['Geolocation'] = df.apply(lambda row: f"{row['Zip Code']}_{row['Latitude']}_{row['Longitude']}", axis=1)

# Codificar la columna Geolocation
geo_encoder = OneHotEncoder()
geo_encoded = geo_encoder.fit_transform(df[['Geolocation']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=geo_encoder.get_feature_names_out(['Geolocation']))

#Eliminar columnas originales


df.drop(columns=['Zip Code', 'Latitude', 'Longitude'], inplace=True)
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Number of Referrals,Tenure in Months,Offer,Phone Service,...,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason,Geolocation
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,2,9,NaN,Yes,...,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN,93225_34.827662_-118.999073
1,0003-MKNFE,Male,46,No,0,Glendale,0,9,NaN,Yes,...,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN,91206_34.162515_-118.203869
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,0,4,Offer E,Yes,...,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices,92627_33.645672_-117.922613
3,0011-IGKFF,Male,78,Yes,0,Martinez,1,13,Offer D,Yes,...,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction,94553_38.014457_-122.115432
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,3,3,NaN,Yes,...,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability,93010_34.227846_-119.079903